### ISSUE TITLE
java.net.MalformedURLException: For input string:

### ISSUE THREAD

**Issue by nkartyshov** [AdguardTeam/AdguardDNS#21]
`2016-08-03 09:43:37,800 ERROR server.DnsRequestWorker Error while processing DNS request
java.net.MalformedURLException: For input string: "mail4.fast.net.id"	
at java.net.URL.<init>(URL.java:630)	
at java.net.URL.<init>(URL.java:493)	
at java.net.URL.<init>(URL.java:442)	
at com.adguard.dns.server.DnsFilter.createFilterContext(DnsFilter.java:154)	
at com.adguard.dns.server.DnsFilter.isBlock(DnsFilter.java:130)	
at com.adguard.dns.server.DnsFilter.filter(DnsFilter.java:88)	
at com.adguard.dns.server.DnsRequestWorker.run(DnsRequestWorker.java:55)	
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)	
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)	
at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NumberFormatException: For input string: "mail4.fast.net.id"	
at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)	
at java.lang.Integer.parseInt(Integer.java:492)	at java.lang.Integer.parseInt(Integer.java:527)	
at java.net.URLStreamHandler.parseURL(URLStreamHandler.java:217)	
at java.net.URL.<init>(URL.java:625)	
... 9 more`

**Comment by nkartyshov** [comment]
fix
