### ISSUE TITLE
java.lang.Exception: Cannot get ParentalControl response for domain name mmi706.whatsapp.net

### ISSUE THREAD

**Issue by nkartyshov** [AdguardTeam/AdguardDNS#22]
```
2016-08-02 09:35:44,182 ERROR server.DnsRequestWorker Error while processing DNS request
java.lang.Exception: Cannot get ParentalControl response for domain name mmi706.whatsapp.net	
at com.adguard.filter.filters.ParentalControlApiClient.lookupDomain(ParentalControlApiClient.java:72)	
at com.adguard.filter.filters.ParentalControlApiClient.getParentalControlInfo(ParentalControlApiClient.java:46)	
at com.adguard.dns.server.DnsFilter.isParentalControl(DnsFilter.java:118)	
at com.adguard.dns.server.DnsFilter.filter(DnsFilter.java:102)	
at com.adguard.dns.server.DnsRequestWorker.run(DnsRequestWorker.java:55)	
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)	
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)	
at java.lang.Thread.run(Thread.java:745)
```

**Comment by nkartyshov** [comment]
fix
