### ISSUE TITLE
Crash instantly when click "Refresh statistics"

### ISSUE THREAD

**Issue by dfmcvn** [AdguardTeam/AdguardDNS#355]
### Steps to reproduce

1. Launch `./AdguardDNS`
2. Go to panel at http://host:port
3. Click Refresh statistics

### Expected behavior

The stats will show up
### Actual behavior

Process crashed

<details><summary>Screenshot:</summary>
![image](https://user-images.githubusercontent.com/22710598/46676214-3d00c500-cc0a-11e8-9cc7-652c1b48fd2f.png)

</details>

### Your environment

CentOS Linux release 7.5.1804 (Core)
go version go1.11.1 linux/amd64
nodejs v10.11.0

|   Description  |     Value    |
| -------------- | ------------ |
| Version of AdGuard DNS server:| v0.1-153-g16fd
| How did you setup DNS configuration:| none
| If it's a router or IoT, please write device model:| none
| Operating system and version:| CentOS 7

#### Log
```
[root@vps192261 AdguardDNS]# ./AdguardDNS
2018/10/09 16:22:57 AdGuard DNS web interface backend, version v0.1-153-g16fd
2018/10/09 16:22:57 Reading YAML file: /root/AdguardDNS/AdguardDNS.yaml
2018/10/09 16:22:57 Writing YAML file: /root/AdguardDNS/AdguardDNS.yaml
2018/10/09 16:22:57 Loading JSON stats: /root/AdguardDNS/stats.json
2018/10/09 16:22:57 Writing DNS config: /root/AdguardDNS/Corefile
2018/10/09 16:22:57 Writing filter file: /root/AdguardDNS/dnsfilter.txt
2018/10/09 16:22:57 coredns PID: xxxx
2018/10/09 16:22:57 Go to http://xxxx:xxxx
2018/10/09 16:22:57 filterFileNames = [dnsfilter.txt]
2018/10/09 16:22:57 Added 0 rules from dnsfilter.txt
.:53
2018/10/09 16:22:57 [INFO] CoreDNS-1.2.2
2018/10/09 16:22:57 [INFO] linux/amd64, go1.11.1,
CoreDNS-1.2.2
linux/amd64, go1.11.1,
2018/10/09 16:22:59 Filter https://filters.adtidy.org/windows/filters/15.txt updated: 444627 bytes, 22373 rules
2018/10/09 16:22:59 Writing filter file: /root/AdguardDNS/dnsfilter.txt
2018/10/09 16:22:59 [INFO] SIGUSR1: Reloading
2018/10/09 16:22:59 [INFO] Reloading
2018/10/09 16:22:59 filterFileNames = [dnsfilter.txt]
2018/10/09 16:22:59 Added 22373 rules from dnsfilter.txt
2018/10/09 16:22:59 [INFO] Reloading complete
panic: assignment to entry in nil map

goroutine 21 [running]:
main.applyDelta(0xdfa520, 0xc00015f860)
        /root/AdguardDNS/stats.go:215 +0x16b
main.collectStats()
        /root/AdguardDNS/stats.go:192 +0x93d
main.statsCollector(0x3b9aca00)
        /root/AdguardDNS/stats.go:81 +0x5e
created by main.runStatsCollectors
        /root/AdguardDNS/stats.go:76 +0x3e
[root@vps192261 AdguardDNS]#

```

**Comment by dfmcvn** [comment]
Update: After pulling commit `c3df81b`, the issue has been resolved :D
