### ISSUE TITLE
EnforceSafeSearchFilter error

### ISSUE THREAD

**Issue by nkartyshov** [AdguardTeam/AdguardDNS#47]
`2016-09-23 00:01:29,051 ERROR server.DnsRequestWorker Error while processing DNS request
java.lang.IllegalArgumentException: invalid IPv6 address
        at org.xbill.DNS.AAAARecord.<init>(AAAARecord.java:35)
        at com.adguard.dns.server.EnforceSafeSearchFilter.modifyDnsRequest(EnforceSafeSearchFilter.java:96)
        at com.adguard.dns.server.DnsRequestWorker.run(DnsRequestWorker.java:70)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
`

**Comment by nkartyshov** [comment]
fixed
