### ISSUE TITLE
NullPointerException in DnsRequestWorker

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardDNS#9]
```
2016-07-26 12:25:14,389 ERROR server.DnsRequestWorker Error while processing DNS request
java.lang.NullPointerException  at 
java.util.concurrent.ConcurrentHashMap.hash(ConcurrentHashMap.java:333)      at 
java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:988)       at 
com.adguard.commons.concurrent.LockManager.getOrCreateObjectLock(LockManager.java:23)        
at com.adguard.commons.concurrent.LockManager.acquireExclusiveLock(LockManager.java:69) 
at com.adguard.filter.filters.SafebrowsingFilter.lookupDomain(SafebrowsingFilter.java:113)      at 
com.adguard.filter.filters.SafebrowsingFilter.filterHttpRequest(SafebrowsingFilter.java:82)  at 
com.adguard.dns.server.DnsFilter.isMalware(DnsFilter.java:137)       at 
com.adguard.dns.server.DnsFilter.filter(DnsFilter.java:92)   at 
com.adguard.dns.server.DnsRequestWorker.run(DnsRequestWorker.java:55)        at 
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)      at 
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)      at 
java.lang.Thread.run(Thread.java:745)
```

**Comment by nkartyshov** [comment]
fix
